using Microsoft.CodeAnalysis.CSharp;
using NUnit.Extensions.Helpers.Generators;
using Shouldly;

namespace NUnit.Extensions.Helpers.Tests;

public class ConstructorParameterNullTestGeneratorTests
{
	[Test]
	public void Generates_Simple_Test()
	{
		var inputCompilation = CreateCSharpCompilation("""
using System;
using System.IO;
using NUnit.Framework;

namespace MyApp
{
	public class Document
	{
		private Stream _stream;

		public Document(Stream myStream)
		{
			_stream = myStream ?? throw new ArgumentNullException(nameof(myStream));
		}
	}	
}

namespace Testing
{
	[GenerateConstructorParameterNullTests(typeof(MyApp.Document))]
	public partial class CtorTests
	{
	}
}
""");

		var generatorResult = TestHelpers.GenerateAndValidateCSharpOutput<ConstructorParameterNullTestGenerator>(inputCompilation, 1, true);

		generatorResult.GeneratedSources[0].HintName.ShouldStartWith("Testing.CtorTests_");
		generatorResult.GeneratedSources[0].SourceText.ToString().Trim().ShouldBe("""
// <auto-generated/>
using System;
using Moq;
using Shouldly;

namespace Testing;
partial class CtorTests
{
	[Test]
	public void Throws_Exception_When_MyStream_Is_Null()
	{
		Action action = () => new Document(null);
		action.ShouldThrow<ArgumentNullException>().ParamName.ShouldBe("myStream");
	}

}
""");

	}

	[Test]
	public void Generates_Test_With_Nested_BaseClass()
	{
		var inputCompilation = CreateCSharpCompilation("""
using System;
using System.IO;
using NUnit.Framework;

namespace MyApp
{
	public class Document
	{
		private Stream _stream;

		public Document(Stream myStream)
		{
			_stream = myStream ?? throw new ArgumentNullException(nameof(myStream));
		}
	}	
}

namespace Testing
{
	public class MyTests
	{

		[GenerateConstructorParameterNullTests(typeof(MyApp.Document))]
		public partial class CtorTests : MyTests
		{
		}
	}
}
""");

		var generatorResult = TestHelpers.GenerateAndValidateCSharpOutput<ConstructorParameterNullTestGenerator>(inputCompilation, 1, true);

		generatorResult.GeneratedSources[0].HintName.ShouldStartWith("Testing.MyTests.CtorTests_");
		generatorResult.GeneratedSources[0].SourceText.ToString().Trim().ShouldBe("""
// <auto-generated/>
using System;
using Moq;
using Shouldly;

namespace Testing;
partial class MyTests
{
	partial class CtorTests : Testing.MyTests
	{
		[Test]
		public void Throws_Exception_When_MyStream_Is_Null()
		{
			Action action = () => new Document(null);
			action.ShouldThrow<ArgumentNullException>().ParamName.ShouldBe("myStream");
		}

	}
}
""");

	}

	[Test]
	public void Generates_Test_With_Multiple_Parameters()
	{
		var inputCompilation = CreateCSharpCompilation("""
using System;
using System.IO;
using NUnit.Framework;

namespace MyApp
{
	public class Document
	{
		private Stream _stream;
		private IFileTester _fileTester;
		private IOtherFilter _filter;

		public Document(Stream myStream, IFileTester fileTester, IOtherFilter filter)
		{
			_stream = myStream ?? throw new ArgumentNullException(nameof(myStream));
			_fileTester = fileTester ?? throw new ArgumentNullException(nameof(fileTester));
			_filter = filter ?? throw new ArgumentNullException(nameof(filter));
		}
	}

	public interface IFileTester {}
	public interface IOtherFilter {}
}

namespace Testing
{
	[GenerateConstructorParameterNullTests(typeof(MyApp.Document))]
	public partial class CtorTests
	{
	}
}
""");

		var generatorResult = TestHelpers.GenerateAndValidateCSharpOutput<ConstructorParameterNullTestGenerator>(inputCompilation, 1, true);

		generatorResult.GeneratedSources[0].SourceText.ToString().Trim().ShouldBe("""
// <auto-generated/>
using System;
using Moq;
using Shouldly;

namespace Testing;
partial class CtorTests
{
	[Test]
	public void Throws_Exception_When_MyStream_Is_Null()
	{
		Action action = () => new Document(null, null, null);
		action.ShouldThrow<ArgumentNullException>().ParamName.ShouldBe("myStream");
	}

	[Test]
	public void Throws_Exception_When_FileTester_Is_Null()
	{
		Action action = () => new Document(Mock.Of<System.IO.Stream>(), null, null);
		action.ShouldThrow<ArgumentNullException>().ParamName.ShouldBe("fileTester");
	}

	[Test]
	public void Throws_Exception_When_Filter_Is_Null()
	{
		Action action = () => new Document(Mock.Of<System.IO.Stream>(), Mock.Of<MyApp.IFileTester>(), null);
		action.ShouldThrow<ArgumentNullException>().ParamName.ShouldBe("filter");
	}

}
""");

	}

	[Test]
	public void Generates_Test_With_File_Scoped_Namespace()
	{
		var inputCompilation = CreateCSharpCompilation("""
using System;
using System.IO;
using NUnit.Framework;

namespace MyApp.Testing;

public class Document
{
	private Stream _stream;

	public Document(Stream myStream)
	{
		_stream = myStream ?? throw new ArgumentNullException(nameof(myStream));
	}
}	


[GenerateConstructorParameterNullTests(typeof(MyApp.Testing.Document))]
public partial class CtorTests
{
}

""");

		var generatorResult = TestHelpers.GenerateAndValidateCSharpOutput<ConstructorParameterNullTestGenerator>(inputCompilation, 1, true);

		generatorResult.GeneratedSources[0].HintName.ShouldStartWith("MyApp.Testing.CtorTests_");
		generatorResult.GeneratedSources[0].SourceText.ToString().Trim().ShouldBe("""
// <auto-generated/>
using System;
using Moq;
using Shouldly;

namespace MyApp.Testing;
partial class CtorTests
{
	[Test]
	public void Throws_Exception_When_MyStream_Is_Null()
	{
		Action action = () => new Document(null);
		action.ShouldThrow<ArgumentNullException>().ParamName.ShouldBe("myStream");
	}

}
""");

	}

	[Test]
	public void Generates_Test_With_Nested_Namespaces()
	{
		var inputCompilation = CreateCSharpCompilation("""
using System;
using System.IO;
using NUnit.Framework;

namespace MyApp
{
	namespace Testing
	{
		public class Document
		{
			private Stream _stream;

			public Document(Stream myStream)
			{
				_stream = myStream ?? throw new ArgumentNullException(nameof(myStream));
			}
		}
	}
}

namespace Testing
{
	namespace OtherNamespace
	{
		[GenerateConstructorParameterNullTests(typeof(MyApp.Testing.Document))]
		public partial class CtorTests
		{
		}
	}
}
""");

		var generatorResult = TestHelpers.GenerateAndValidateCSharpOutput<ConstructorParameterNullTestGenerator>(inputCompilation, 1, true);

		generatorResult.GeneratedSources[0].HintName.ShouldStartWith("Testing.OtherNamespace.CtorTests_");
		generatorResult.GeneratedSources[0].SourceText.ToString().Trim().ShouldBe("""
// <auto-generated/>
using System;
using Moq;
using Shouldly;

namespace Testing.OtherNamespace;
partial class CtorTests
{
	[Test]
	public void Throws_Exception_When_MyStream_Is_Null()
	{
		Action action = () => new Document(null);
		action.ShouldThrow<ArgumentNullException>().ParamName.ShouldBe("myStream");
	}

}
""");

	}

	[Test]
	public void Throws_Error_When_Class_Is_Not_Partial()
	{
		var inputCompilation = CreateCSharpCompilation("""
using System;
using System.IO;
using NUnit.Framework;

namespace MyApp
{
	public class Document
	{
		private Stream _stream;

		public Document(Stream myStream)
		{
			_stream = myStream ?? throw new ArgumentNullException(nameof(myStream));
		}
	}	
}

namespace Testing
{
	[GenerateConstructorParameterNullTests(typeof(MyApp.Document))]
	public class CtorTests
	{
	}
}
""");

		var generatorResult = TestHelpers.GenerateCSharpOutput<ConstructorParameterNullTestGenerator>(inputCompilation);
		generatorResult.Diagnostics.ShouldNotBeEmpty();
		generatorResult.Diagnostics.ShouldContain(d => d.Id == "NEG101" && d.ToString() == "error NEG101: The class Testing.CtorTests should be partial");
	}

	[Test]
	public void Throws_Error_When_Nested_Class_Is_Not_Partial()
	{
		var inputCompilation = CreateCSharpCompilation("""
using System;
using System.IO;
using NUnit.Framework;

namespace MyApp
{
	public class Document
	{
		private Stream _stream;

		public Document(Stream myStream)
		{
			_stream = myStream ?? throw new ArgumentNullException(nameof(myStream));
		}
	}	
}

namespace Testing
{
	public class OtherTest
	{
		[GenerateConstructorParameterNullTests(typeof(MyApp.Document))]
		public class CtorTests
		{
		}
	}
}
""");

		var generatorResult = TestHelpers.GenerateCSharpOutput<ConstructorParameterNullTestGenerator>(inputCompilation);
		generatorResult.Diagnostics.ShouldNotBeEmpty();
		generatorResult.Diagnostics.ShouldContain(d => d.Id == "NEG101" && d.ToString() == "error NEG101: The class Testing.OtherTest.CtorTests should be partial");
	}

	[Test]
	public void Generates_Tests_In_Nested_Class()
	{
		var inputCompilation = CreateCSharpCompilation("""
using System;
using System.IO;
using NUnit.Framework;

namespace MyApp
{
	public class Document
	{
		private Stream _stream;

		public Document(Stream myStream)
		{
			_stream = myStream ?? throw new ArgumentNullException(nameof(myStream));
		}
	}	
}

namespace Testing
{
	[GenerateConstructorParameterNullTests(typeof(MyApp.Document), AsNestedClass = true)]
	public partial class MyTests
	{
	}
}
""");

		var generatorResult = TestHelpers.GenerateAndValidateCSharpOutput<ConstructorParameterNullTestGenerator>(inputCompilation, 1, true);

		generatorResult.GeneratedSources[0].HintName.ShouldStartWith("Testing.MyTests_");
		generatorResult.GeneratedSources[0].SourceText.ToString().Trim().ShouldBe("""
// <auto-generated/>
using System;
using Moq;
using Shouldly;

namespace Testing;
partial class MyTests
{
	class ConstructorParameterNullTests
	{
		[Test]
		public void Throws_Exception_When_MyStream_Is_Null()
		{
			Action action = () => new Document(null);
			action.ShouldThrow<ArgumentNullException>().ParamName.ShouldBe("myStream");
		}

	}
}
""");

	}

	private static CSharpCompilation CreateCSharpCompilation(string source)
	{
		return TestHelpers.CreateCSharpCompilation(source, Sources.GENERATE_CONSTRUCTOR_PARAMETER_NULL_TESTS_ATTRIBUTE_SOURCE);
	}
}